language: ruby
rvm:
  - 2.1.8
cache: bundler
services:
  - postgresql
  - redis-server
addons:
  postgresql: '9.3'
before_script:
  - cp .env.example .env
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake db:migrate
env:
  - DISPLAY=:99.0
script:
  - bundle exec rspec
